version: '3'

services:
  jenkins:
    container_name: ${APP_NAME}
    image: jenkins/jenkins:${APP_VERSION}
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    user: root
    networks:
      - infra
    restart: always
    ports:
      - "$APP_JENKINS_SLAVE_AGENT_PORT:50000"
      - "$APP_HTTP_PORT:8080"
    volumes:
      - jenkins:/var/jenkins_home

networks:
  infra:
    external: true

volumes:
  jenkins:
    driver: local
