 # docker-compose.yaml
version: '3.0'
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    networks:
      - infra
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  infra:
    external: true
volumes:
  nexus-data:
