version: "3.0"
services:
  vault-server:
    image: vault:latest
    ports:
      - "8200:8200"
    networks:
      - infra   
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
    cap_add:
      - IPC_LOCK
    deploy:
      placement:
        constraints: [node.role != manager] 
networks:
  infra:
    external: true
